all:
  hosts:
    nfs01.engwsc.example.com:
    vmm[01:02].engwsc.example.com:
    user[01:04].engwsc.example.com:
    comp[01:04].engwsc.example.com:
    idm.engwsc.example.com:
    gitlab.engwsc.example.com:
    slurm.engwsc.example.com:
    graylog.engwsc.example.com:
    ansible.engwsc.example.com:
    influxdb.engwsc.example.com:
    grafana.engwsc.example.com:
    docker.engwsc.example.com:
    mirror.engwsc.example.com:

  children:
    vmm_nodes:
      hosts:
        vmm[01:02].engwsc.example.com:

    user_nodes:
      hosts:
        user[01:04].engwsc.example.com:

    comp_nodes:
      hosts:
        comp[01:04].engwsc.example.com:

    storage_nodes:
      hosts:
        nfs01.engwsc.example.com:

    service_nodes:
      hosts:
        idm.engwsc.example.com:
        gitlab.engwsc.example.com:
        slurm.engwsc.example.com:
        graylog.engwsc.example.com:
        ansible.engwsc.example.com:
        influxdb.engwsc.example.com:
        grafana.engwsc.example.com:
        docker.engwsc.example.com:
        mirror.engwsc.example.com:

    idm_servers:
      hosts:
        idm.engwsc.example.com:

    idm_clients:
      hosts:
        nfs01.engwsc.example.com:
        vmm[01:02].engwsc.example.com:
        user[01:04].engwsc.example.com:
        comp[01:04].engwsc.example.com:
        idm.engwsc.example.com:
        gitlab.engwsc.example.com:
        slurm.engwsc.example.com:
        graylog.engwsc.example.com:
        ansible.engwsc.example.com:
        influxdb.engwsc.example.com:
        grafana.engwsc.example.com:
        docker.engwsc.example.com:
        mirror.engwsc.example.com:

    gitlab_servers:
      hosts:
        gitlab.engwsc.example.com:

    slurm_controllers:
      hosts:
        slurm.engwsc.example.com:

    slurm_clients:
      children:
        user_nodes:
        comp_nodes:

    graylog_servers:
      hosts:
        graylog.engwsc.example.com:

    rsyslog_clients:
      hosts:
        nfs01.engwsc.example.com:
        vmm[01:02].engwsc.example.com:
        user[01:04].engwsc.example.com:
        comp[01:04].engwsc.example.com:
        idm.engwsc.example.com:
        gitlab.engwsc.example.com:
        slurm.engwsc.example.com:
        graylog.engwsc.example.com:
        ansible.engwsc.example.com:
        influxdb.engwsc.example.com:
        grafana.engwsc.example.com:
        docker.engwsc.example.com:
        mirror.engwsc.example.com:

    ansible_controllers:
      hosts:
        ansible.engwsc.example.com:

    influxdb_servers:
      hosts:
        influxdb.engwsc.example.com:

    telegraf_clients:
      hosts:
        nfs01.engwsc.example.com:
        vmm[01:02].engwsc.example.com:
        user[01:04].engwsc.example.com:
        comp[01:04].engwsc.example.com:
        idm.engwsc.example.com:
        gitlab.engwsc.example.com:
        slurm.engwsc.example.com:
        graylog.engwsc.example.com:
        ansible.engwsc.example.com:
        influxdb.engwsc.example.com:
        grafana.engwsc.example.com:
        docker.engwsc.example.com:
        mirror.engwsc.example.com:

    grafana_servers:
      hosts:
        grafana.engwsc.example.com:

    docker_servers:
      hosts:
        docker.engwsc.example.com:

    mirror_servers:
      hosts:
        mirror.engwsc.example.com:
